{
 "title": "Server Metrics",
 "description": "General metrics for the server as a whole",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Connections Made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "lt_total_connections", "legendFormat": "Connections" }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "lt_active_connections", "legendFormat": "Connections" }
   ]
  },
  {
   "title": "Total Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "lt_messages_total", "legendFormat": "Messages" }
   ]
  },
  {
   "title": "Connection Duration (s)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le) (increase(lt_connection_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(lt_connection_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90,sum(rate(lt_connection_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50,sum(rate(lt_connection_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Message Processing Time (s)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(lt_message_processing_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Out Of Sync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "lt_server_oos", "legendFormat": "Value" }
   ]
  },
  {
   "title": "Total Message Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "lt_message_size_bytes_sum", "legendFormat": "Value" }
   ]
  },
  {
   "title": "WebSocket Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "lt_websocket_errors", "legendFormat": "Errors" }
   ]
  },
  {
   "title": "400 Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "lt_400_errors", "legendFormat": "Errors" }
   ]
  },
  {
   "title": "500 Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "lt_500_errors", "legendFormat": "Errors" }
   ]
  }
 ]
}