{
 "title": "Performance",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "lt_memory_usage_bytes", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Heal Allocation Rate",
   "type": "timeseries",
   "description": "How quickly your application is allocating memory. This can help you spot memory leaks and optimize memory usage.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_heap_alloc_bytes[$__rate_interval])",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "The number of concurrent tasks your application is running. A sudden, unexplained spike can indicate a resource leak or a deadlock.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "Routines" }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "timeseries",
   "description": "The 95th percentile of how long your application is paused for garbage collection. A high value means your app is spending too much time cleaning up memory instead of doing work.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(quantile) (rate(go_gc_duration_seconds[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}